name : LinkByNet
description : LinkByNet's engineering blog

kramdown:
    input: GFM

gems:
    - jekyll-sitemap
    - jekull-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

theme: jekyll-theme-merlot
