name : LinkByNet
description : LinkByNet's engineering blog

kramdown:
    input: GFM

gems:
    - jekyll-sitemap
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
