name : LinkByNet
description : LinkByNet's engineering blog

kramdown:
    input: GFM
    toc_levels : 1..4

gems:
    - jekyll-sitemap
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

authors:
    skattoor:
        display_name: Stéphane KATTOOR
        twitter: StephaneLBN
        gravatar_id: 819bb0fd44e74b7ba819ccc2a9c7020b

linkbynet_logo: LBN_Gris_Horizontal2.png

linkbynet_blob: >
    <p> <a href="http://www.linkbynet.com">LINKBYNET</a> is an IT watchmaker that
    can assist you with talent in your digital transformation. We build
    best-of-breed architectures and orchestrate your applications with
    precision, reliability and quality.  Innovation, Best of Breed Services and
    Enhanced Cloud, we invent and implement a whole set of services to meet all
    your needs.</p>
